spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yml
logging.level.ru.alexadler.tgnotificationmanagerbot.listener=debug
logging.level.ru.alexadler.tgnotificationmanagerbot.service=debug
telegram.bot.token=